---
- name: deploy vsftpd
  hosts: target1
  tasks:
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: Copy using inline content
    copy:
      content: "this is ridiculous"
      dest: /etc/dwightaa.txt

