---
- name: deploy vsftpd
  hosts: target1
  tasks: 
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: create readme file for dwight
    copy:
      content: "this is modified by dwight. wha Awesome!\n"
      dest: /var/ftp/pub/README.DWIGHT
      force: no
      mode: 0444
...
